import {
  CalendarCheck,
  ClipboardList,
  UserCheck,
  UserPlus,
} from 'lucide-react'

export const crmDashboardStats = [
  {
    label: 'Tổng Lead',
    value: '1,248',
    trend: '+86 lead trong tuần',
    icon: ClipboardList,
    color: 'blue',
  },
  {
    label: 'Lead mới hôm nay',
    value: '32',
    trend: '12 lead chưa phân Sale',
    icon: UserPlus,
    color: 'emerald',
  },
  {
    label: 'Khách hàng',
    value: '418',
    trend: '+18 khách hàng tháng này',
    icon: UserCheck,
    color: 'rose',
  },
  {
    label: 'Lịch chăm sóc hôm nay',
    value: '24',
    trend: '5 việc cần ưu tiên',
    icon: CalendarCheck,
    color: 'amber',
  },
]

export const leadChartPeriods = [
  {
    label: 'Theo ngày',
    dataKey: 'day',
    data: [
      { label: 'T2', leads: 42 },
      { label: 'T3', leads: 55 },
      { label: 'T4', leads: 48 },
      { label: 'T5', leads: 63 },
      { label: 'T6', leads: 71 },
      { label: 'T7', leads: 39 },
      { label: 'CN', leads: 28 },
    ],
  },
  {
    label: 'Theo tuần',
    dataKey: 'week',
    data: [
      { label: 'Tuần 1', leads: 214 },
      { label: 'Tuần 2', leads: 268 },
      { label: 'Tuần 3', leads: 241 },
      { label: 'Tuần 4', leads: 306 },
    ],
  },
  {
    label: 'Theo tháng',
    dataKey: 'month',
    data: [
      { label: 'T3', leads: 780 },
      { label: 'T4', leads: 846 },
      { label: 'T5', leads: 912 },
      { label: 'T6', leads: 988 },
      { label: 'T7', leads: 1_064 },
      { label: 'T8', leads: 1_148 },
    ],
  },
]

export const leadStatusData = [
  { name: 'Mới', value: 22, fill: '#2563eb' },
  { name: 'Đang liên hệ', value: 18, fill: '#f59e0b' },
  { name: 'Đã tư vấn', value: 16, fill: '#8b5cf6' },
  { name: 'Đã hẹn kiểm tra', value: 14, fill: '#06b6d4' },
  { name: 'Đã học thử', value: 12, fill: '#f97316' },
  { name: 'Đã chuyển thành khách hàng', value: 10, fill: '#10b981' },
  { name: 'Không có nhu cầu', value: 8, fill: '#ef4444' },
]

export const todayCareSchedules = [
  { time: '09:00', customer: 'Nguyễn Văn A', content: 'Gọi tư vấn' },
  { time: '14:00', customer: 'Trần Thị B', content: 'Nhắc học thử' },
  { time: '16:30', customer: 'Lê Văn C', content: 'Chăm sóc sau tư vấn' },
  { time: '17:15', customer: 'Vũ Hà My', content: 'Xác nhận lịch đóng học phí' },
  { time: '19:00', customer: 'Phan Anh Khoa', content: 'Gửi tài liệu sau học thử' },
]

export const latestLeads = [
  {
    name: 'Phạm Minh Anh',
    birthDate: '18/04/2012',
    school: 'THCS Nguyễn Du',
    className: '8A2',
    phone: '0901 234 567',
    parent: 'Phạm Thu Hương',
    parentEmail: 'huong.pham@example.com',
    address: 'Quận 3, TP.HCM',
    interestedCourse: 'IELTS Foundation',
    availableSchedule: 'Tối T2, T4, T6',
    note: 'Muốn kiểm tra đầu vào trước khi xếp lớp.',
    source: 'Facebook',
    sale: 'Thanh Hà',
    status: 'Mới',
    createdAt: '13/08/2026',
  },
  {
    name: 'Nguyễn Hoàng Nam',
    birthDate: '22/09/2010',
    school: 'THCS Lê Quý Đôn',
    className: '9B1',
    phone: '0918 456 222',
    parent: 'Nguyễn Văn Hùng',
    parentEmail: 'hung.nguyen@example.com',
    address: 'Quận Bình Thạnh, TP.HCM',
    interestedCourse: 'Giao tiếp cơ bản',
    availableSchedule: 'Chiều T3, T5',
    note: 'Phụ huynh cần tư vấn lộ trình giao tiếp hè.',
    source: 'Website',
    sale: 'Quốc Việt',
    status: 'Đang liên hệ',
    createdAt: '13/08/2026',
  },
  {
    name: 'Đỗ Thảo Linh',
    birthDate: '05/01/2015',
    school: 'Tiểu học Trần Quốc Toản',
    className: '5C',
    phone: '0933 120 456',
    parent: 'Đỗ Mai Lan',
    parentEmail: 'lan.do@example.com',
    address: 'Quận 10, TP.HCM',
    interestedCourse: 'Starter Kids',
    availableSchedule: 'Sáng T7, CN',
    note: 'Đã đồng ý lịch kiểm tra đầu vào cuối tuần.',
    source: 'Zalo',
    sale: 'Minh Tú',
    status: 'Đã hẹn kiểm tra',
    createdAt: '12/08/2026',
  },
  {
    name: 'Lê Gia Huy',
    birthDate: '12/07/2011',
    school: 'THCS Colette',
    className: '8B',
    phone: '0987 332 118',
    parent: 'Lê Quốc Bảo',
    parentEmail: 'bao.le@example.com',
    address: 'Quận Phú Nhuận, TP.HCM',
    interestedCourse: 'Foundation Teens',
    availableSchedule: 'Tối T3, T5',
    note: 'Bạn bè giới thiệu, cần gửi học phí chi tiết.',
    source: 'Referral',
    sale: 'Thanh Hà',
    status: 'Mới',
    createdAt: '12/08/2026',
  },
  {
    name: 'Trần Bảo Ngọc',
    birthDate: '30/11/2009',
    school: 'THCS Võ Trường Toản',
    className: '10A1',
    phone: '0976 540 889',
    parent: 'Trần Thị Mai',
    parentEmail: 'mai.tran@example.com',
    address: 'Quận 7, TP.HCM',
    interestedCourse: 'IELTS Intensive',
    availableSchedule: 'Chưa xác định',
    note: 'Tạm dừng vì chưa có nhu cầu học trong tháng này.',
    source: 'Landing page',
    sale: 'Quốc Việt',
    status: 'Không có nhu cầu',
    createdAt: '11/08/2026',
  },
  {
    name: 'Hoàng Minh Quân',
    birthDate: '14/03/2008',
    school: 'THPT Gia Định',
    className: '11A4',
    phone: '0906 812 345',
    parent: 'Hoàng Đức Anh',
    parentEmail: 'anh.hoang@example.com',
    address: 'Quận Gò Vấp, TP.HCM',
    interestedCourse: 'Giao tiếp nâng cao',
    availableSchedule: 'Tối T2, T6',
    note: 'Cần tư vấn học giao tiếp phục vụ phỏng vấn.',
    source: 'TikTok',
    sale: 'Minh Tú',
    status: 'Đã tư vấn',
    createdAt: '11/08/2026',
  },
  {
    name: 'Bùi Khánh Vy',
    birthDate: '09/06/2016',
    school: 'Tiểu học Nguyễn Bỉnh Khiêm',
    className: '4A',
    phone: '0912 778 909',
    parent: 'Bùi Ngọc Trâm',
    parentEmail: 'tram.bui@example.com',
    address: 'TP. Thủ Đức, TP.HCM',
    interestedCourse: 'Starter Kids',
    availableSchedule: 'Sáng CN',
    note: 'Đã đặt lịch học thử.',
    source: 'Facebook',
    sale: 'Thanh Hà',
    status: 'Đã học thử',
    createdAt: '10/08/2026',
  },
  {
    name: 'Ngô Tuấn Anh',
    birthDate: '25/08/2010',
    school: 'THCS Trần Văn Ơn',
    className: '9A3',
    phone: '0981 220 771',
    parent: 'Ngô Minh Đức',
    parentEmail: 'duc.ngo@example.com',
    address: 'Quận 1, TP.HCM',
    interestedCourse: 'IELTS Foundation',
    availableSchedule: 'Tối T4, T7',
    note: 'Ưu tiên lớp sĩ số nhỏ.',
    source: 'Website',
    sale: 'Quốc Việt',
    status: 'Mới',
    createdAt: '10/08/2026',
  },
  {
    name: 'Mai Phương Nhi',
    birthDate: '17/12/2012',
    school: 'THCS Hoàng Hoa Thám',
    className: '8C',
    phone: '0937 612 340',
    parent: 'Mai Thanh Bình',
    parentEmail: 'binh.mai@example.com',
    address: 'Quận Tân Bình, TP.HCM',
    interestedCourse: 'Foundation Teens',
    availableSchedule: 'Chiều T7',
    note: 'Đang so sánh lịch học với lớp hiện tại.',
    source: 'Zalo',
    sale: 'Minh Tú',
    status: 'Đang liên hệ',
    createdAt: '09/08/2026',
  },
  {
    name: 'Đinh Nhật Minh',
    birthDate: '02/05/2007',
    school: 'THPT Nguyễn Thượng Hiền',
    className: '12D1',
    phone: '0978 223 110',
    parent: 'Đinh Thảo Nguyên',
    parentEmail: 'nguyen.dinh@example.com',
    address: 'Quận Tân Phú, TP.HCM',
    interestedCourse: 'IELTS Intensive',
    availableSchedule: 'Tối T3, T5, CN',
    note: 'Mục tiêu IELTS 6.5 trong 6 tháng.',
    source: 'Referral',
    sale: 'Thanh Hà',
    status: 'Đã chuyển thành khách hàng',
    createdAt: '09/08/2026',
  },
]

export const newestCustomers = [
  {
    name: 'Vũ Hà My',
    course: 'IELTS Foundation',
    registeredAt: '12/08/2026',
    sale: 'Minh Tú',
    parent: { name: 'Vũ Thanh Tâm', phone: '0908 661 220', email: 'tam.vu@example.com', address: 'Quận 5, TP.HCM' },
    tuition: { package: '24 buổi', total: '12.000.000đ', paid: '6.000.000đ', debt: '6.000.000đ', nextDue: '25/08/2026' },
    contract: { code: 'HD-2026-0812-01', status: 'Đã ký', signedAt: '12/08/2026', expireAt: '12/02/2027' },
    progress: { className: 'IELTS FDN-08', completed: '2/24 buổi', attendance: '100%', teacherNote: 'Nắm nền tảng tốt, cần luyện thêm speaking.' },
    careHistory: [
      { date: '12/08/2026', content: 'Gửi hợp đồng và lịch học', staff: 'Minh Tú' },
      { date: '13/08/2026', content: 'Nhắc lịch buổi học đầu tiên', staff: 'CSKH' },
    ],
  },
  {
    name: 'Phan Anh Khoa',
    course: 'Starter Kids',
    registeredAt: '12/08/2026',
    sale: 'Thanh Hà',
    parent: { name: 'Phan Thu Trang', phone: '0916 204 333', email: 'trang.phan@example.com', address: 'TP. Thủ Đức, TP.HCM' },
    tuition: { package: '20 buổi', total: '8.500.000đ', paid: '8.500.000đ', debt: '0đ', nextDue: '—' },
    contract: { code: 'HD-2026-0812-02', status: 'Đã ký', signedAt: '12/08/2026', expireAt: '12/01/2027' },
    progress: { className: 'Kids ST-12', completed: '1/20 buổi', attendance: '100%', teacherNote: 'Hòa nhập nhanh, phản xạ tốt.' },
    careHistory: [
      { date: '12/08/2026', content: 'Xác nhận nhập học', staff: 'Thanh Hà' },
      { date: '14/08/2026', content: 'Gửi tài liệu buổi 1', staff: 'CSKH' },
    ],
  },
  {
    name: 'Nguyễn Tuấn Kiệt',
    course: 'Giao tiếp cơ bản',
    registeredAt: '11/08/2026',
    sale: 'Quốc Việt',
    parent: { name: 'Nguyễn Minh Châu', phone: '0982 447 119', email: 'chau.nguyen@example.com', address: 'Quận 4, TP.HCM' },
    tuition: { package: '18 buổi', total: '7.200.000đ', paid: '3.600.000đ', debt: '3.600.000đ', nextDue: '28/08/2026' },
    contract: { code: 'HD-2026-0811-01', status: 'Chờ bổ sung chữ ký', signedAt: '11/08/2026', expireAt: '11/01/2027' },
    progress: { className: 'COMM-BASIC-09', completed: '2/18 buổi', attendance: '100%', teacherNote: 'Cần luyện phát âm âm cuối.' },
    careHistory: [
      { date: '11/08/2026', content: 'Tư vấn gói học phí', staff: 'Quốc Việt' },
      { date: '13/08/2026', content: 'Nhắc bổ sung hợp đồng bản cứng', staff: 'CSKH' },
    ],
  },
  {
    name: 'Đặng Bảo Châu',
    course: 'IELTS Intensive',
    registeredAt: '11/08/2026',
    sale: 'Minh Tú',
    parent: { name: 'Đặng Hoàng Nam', phone: '0973 810 552', email: 'nam.dang@example.com', address: 'Quận 8, TP.HCM' },
    tuition: { package: '32 buổi', total: '18.000.000đ', paid: '9.000.000đ', debt: '9.000.000đ', nextDue: '30/08/2026' },
    contract: { code: 'HD-2026-0811-02', status: 'Đã ký', signedAt: '11/08/2026', expireAt: '11/04/2027' },
    progress: { className: 'IELTS INT-03', completed: '1/32 buổi', attendance: '100%', teacherNote: 'Mục tiêu 6.5, cần theo sát writing.' },
    careHistory: [
      { date: '11/08/2026', content: 'Chốt lớp Intensive', staff: 'Minh Tú' },
      { date: '12/08/2026', content: 'Gửi checklist tài liệu IELTS', staff: 'CSKH' },
    ],
  },
  {
    name: 'Lý Gia Bảo',
    course: 'Foundation Teens',
    registeredAt: '10/08/2026',
    sale: 'Thanh Hà',
    parent: { name: 'Lý Minh Hạnh', phone: '0938 990 225', email: 'hanh.ly@example.com', address: 'Quận 11, TP.HCM' },
    tuition: { package: '24 buổi', total: '10.800.000đ', paid: '10.800.000đ', debt: '0đ', nextDue: '—' },
    contract: { code: 'HD-2026-0810-01', status: 'Đã ký', signedAt: '10/08/2026', expireAt: '10/02/2027' },
    progress: { className: 'FDN-TEENS-02', completed: '3/24 buổi', attendance: '100%', teacherNote: 'Từ vựng tốt, cần tăng phản xạ nghe.' },
    careHistory: [
      { date: '10/08/2026', content: 'Hoàn tất thanh toán', staff: 'Thanh Hà' },
      { date: '13/08/2026', content: 'Hỏi thăm sau 2 buổi học', staff: 'CSKH' },
    ],
  },
  {
    name: 'Cao Minh Ngọc',
    course: 'Starter Kids',
    registeredAt: '10/08/2026',
    sale: 'Quốc Việt',
    parent: { name: 'Cao Thị Hồng', phone: '0902 555 610', email: 'hong.cao@example.com', address: 'Quận 6, TP.HCM' },
    tuition: { package: '20 buổi', total: '8.500.000đ', paid: '4.250.000đ', debt: '4.250.000đ', nextDue: '24/08/2026' },
    contract: { code: 'HD-2026-0810-02', status: 'Đã ký', signedAt: '10/08/2026', expireAt: '10/01/2027' },
    progress: { className: 'Kids ST-12', completed: '2/20 buổi', attendance: '50%', teacherNote: 'Vắng 1 buổi, cần học bù phát âm.' },
    careHistory: [
      { date: '10/08/2026', content: 'Xác nhận lịch học', staff: 'Quốc Việt' },
      { date: '12/08/2026', content: 'Sắp lịch học bù', staff: 'CSKH' },
    ],
  },
  {
    name: 'Hồ Nhật Linh',
    course: 'IELTS Foundation',
    registeredAt: '09/08/2026',
    sale: 'Minh Tú',
    parent: { name: 'Hồ Phương Anh', phone: '0911 378 842', email: 'anh.ho@example.com', address: 'Quận Tân Bình, TP.HCM' },
    tuition: { package: '24 buổi', total: '12.000.000đ', paid: '6.000.000đ', debt: '6.000.000đ', nextDue: '23/08/2026' },
    contract: { code: 'HD-2026-0809-01', status: 'Đã ký', signedAt: '09/08/2026', expireAt: '09/02/2027' },
    progress: { className: 'IELTS FDN-08', completed: '3/24 buổi', attendance: '100%', teacherNote: 'Reading ổn, cần luyện speaking part 2.' },
    careHistory: [
      { date: '09/08/2026', content: 'Chuyển đổi từ học thử', staff: 'Minh Tú' },
      { date: '13/08/2026', content: 'Gửi nhận xét giáo viên', staff: 'CSKH' },
    ],
  },
]
