import {
  AlertTriangle,
  BadgeCheck,
  CalendarClock,
  ClipboardCheck,
  FileText,
  Megaphone,
  ReceiptText,
  ShieldCheck,
  UserPlus,
  Users,
} from 'lucide-react'

export const notificationFilters = [
  { value: 'all', label: 'Tất cả' },
  { value: 'unread', label: 'Chưa đọc' },
  { value: 'urgent', label: 'Khẩn cấp' },
]

export const notificationToneStyles = {
  blue: 'bg-blue-50 text-blue-700 ring-blue-100',
  emerald: 'bg-emerald-50 text-emerald-700 ring-emerald-100',
  amber: 'bg-amber-50 text-amber-700 ring-amber-100',
  red: 'bg-red-50 text-red-700 ring-red-100',
  violet: 'bg-violet-50 text-violet-700 ring-violet-100',
  cyan: 'bg-cyan-50 text-cyan-700 ring-cyan-100',
  slate: 'bg-slate-100 text-slate-700 ring-slate-200',
  fuchsia: 'bg-fuchsia-50 text-fuchsia-700 ring-fuchsia-100',
}

export const notifications = [
  {
    id: 'noti-lead-new-001',
    type: 'lead',
    title: 'Lead mới từ Website',
    message: 'Phạm Minh Anh vừa để lại thông tin tư vấn khóa IELTS Foundation.',
    time: '2 phút trước',
    priority: 'urgent',
    status: 'unread',
    actionLabel: 'Phân Sale',
    tone: 'blue',
    icon: UserPlus,
    detail: {
      code: 'LEAD-2026-0815-01',
      createdAt: '15/08/2026 08:46',
      source: 'Website',
      owner: 'Chưa phân Sale',
      priorityLabel: 'Cần xử lý ngay',
      content: 'Phụ huynh cần tư vấn lộ trình IELTS Foundation cho học viên lớp 8, ưu tiên kiểm tra đầu vào trong tuần này.',
      fields: [
        { label: 'Học viên', value: 'Phạm Minh Anh' },
        { label: 'Phụ huynh', value: 'Phạm Thu Hương' },
        { label: 'Số điện thoại', value: '0901 234 567' },
        { label: 'Khóa quan tâm', value: 'IELTS Foundation' },
      ],
    },
  },
  {
    id: 'noti-lead-follow-002',
    type: 'lead',
    title: 'Lead quá hạn chăm sóc',
    message: 'Nguyễn Hoàng Nam chưa được gọi lại sau 24 giờ kể từ lần tư vấn gần nhất.',
    time: '18 phút trước',
    priority: 'urgent',
    status: 'unread',
    actionLabel: 'Mở lịch chăm sóc',
    tone: 'red',
    icon: AlertTriangle,
    detail: {
      code: 'CARE-OVERDUE-002',
      createdAt: '15/08/2026 08:30',
      source: 'CRM tự động',
      owner: 'Quốc Việt',
      priorityLabel: 'Quá hạn SLA',
      content: 'Lead đã được tư vấn nhưng chưa có lịch gọi lại. Hệ thống cảnh báo để tránh mất cơ hội chuyển đổi.',
      fields: [
        { label: 'Khách hàng', value: 'Nguyễn Hoàng Nam' },
        { label: 'Trạng thái lead', value: 'Đang liên hệ' },
        { label: 'Lần chăm sóc gần nhất', value: '14/08/2026 08:20' },
        { label: 'Việc cần làm', value: 'Gọi lại và cập nhật kết quả tư vấn' },
      ],
    },
  },
  {
    id: 'noti-schedule-start-003',
    type: 'schedule',
    title: 'Lớp sắp bắt đầu',
    message: 'IELTS FDN-08 bắt đầu lúc 19:30 tại Phòng 201, Cơ sở 1.',
    time: '35 phút trước',
    priority: 'normal',
    status: 'unread',
    actionLabel: 'Xem lịch',
    tone: 'amber',
    icon: CalendarClock,
    detail: {
      code: 'SCH-REMINDER-003',
      createdAt: '15/08/2026 08:13',
      source: 'Lịch học',
      owner: 'CSKH',
      priorityLabel: 'Nhắc trước giờ học',
      content: 'Lớp sắp bắt đầu, cần kiểm tra phòng học, thiết bị và trạng thái giáo viên trước khi học viên đến.',
      fields: [
        { label: 'Lớp', value: 'IELTS FDN-08' },
        { label: 'Thời gian', value: '15/08/2026 19:30 - 21:00' },
        { label: 'Phòng', value: 'Phòng 201, Cơ sở 1' },
        { label: 'Giáo viên', value: 'Nguyễn Văn A' },
      ],
    },
  },
  {
    id: 'noti-attendance-004',
    type: 'attendance',
    title: 'Chưa hoàn tất điểm danh',
    message: 'Lớp Kids ST-12 còn 4 học viên chưa được cập nhật trạng thái điểm danh.',
    time: '1 giờ trước',
    priority: 'normal',
    status: 'unread',
    actionLabel: 'Điểm danh',
    tone: 'cyan',
    icon: ClipboardCheck,
    detail: {
      code: 'ATT-2026-0815-004',
      createdAt: '15/08/2026 07:48',
      source: 'Điểm danh',
      owner: 'Giáo viên phụ trách',
      priorityLabel: 'Cần hoàn tất trong ngày',
      content: 'Buổi học đã kết thúc nhưng danh sách điểm danh chưa đủ. Cần cập nhật để gửi báo cáo cho phụ huynh.',
      fields: [
        { label: 'Lớp', value: 'Kids ST-12' },
        { label: 'Đã điểm danh', value: '14/18 học viên' },
        { label: 'Còn thiếu', value: '4 học viên' },
        { label: 'Hạn xử lý', value: '15/08/2026 21:30' },
      ],
    },
  },
  {
    id: 'noti-tuition-due-005',
    type: 'finance',
    title: 'Học phí đến hạn',
    message: '3 học viên có hạn thanh toán trong hôm nay, tổng công nợ 18.250.000đ.',
    time: '2 giờ trước',
    priority: 'urgent',
    status: 'unread',
    actionLabel: 'Xem công nợ',
    tone: 'red',
    icon: ReceiptText,
    detail: {
      code: 'FIN-DUE-005',
      createdAt: '15/08/2026 07:00',
      source: 'Tài chính',
      owner: 'Bộ phận Tài chính',
      priorityLabel: 'Đến hạn hôm nay',
      content: 'Các khoản học phí đến hạn cần được nhắc thanh toán và cập nhật trạng thái thu tiền trong hệ thống.',
      fields: [
        { label: 'Số học viên', value: '3 học viên' },
        { label: 'Tổng công nợ', value: '18.250.000đ' },
        { label: 'Hạn thanh toán', value: '15/08/2026' },
        { label: 'Trạng thái', value: 'Chưa gửi nhắc phí' },
      ],
    },
  },
  {
    id: 'noti-payment-006',
    type: 'finance',
    title: 'Ghi nhận thanh toán',
    message: 'Phan Anh Khoa đã thanh toán đủ gói Starter Kids 20 buổi.',
    time: '3 giờ trước',
    priority: 'normal',
    status: 'read',
    actionLabel: 'Xem biên nhận',
    tone: 'emerald',
    icon: BadgeCheck,
    detail: {
      code: 'PAY-2026-0815-006',
      createdAt: '15/08/2026 05:42',
      source: 'Tài chính',
      owner: 'Thu ngân',
      priorityLabel: 'Đã hoàn tất',
      content: 'Khoản thanh toán đã được ghi nhận đủ, có thể xuất biên nhận và cập nhật hồ sơ học viên.',
      fields: [
        { label: 'Học viên', value: 'Phan Anh Khoa' },
        { label: 'Gói học', value: 'Starter Kids 20 buổi' },
        { label: 'Số tiền', value: '8.500.000đ' },
        { label: 'Phương thức', value: 'Chuyển khoản' },
      ],
    },
  },
  {
    id: 'noti-contract-007',
    type: 'contract',
    title: 'Hợp đồng chờ bổ sung chữ ký',
    message: 'Hợp đồng HD-2026-0811-01 của Nguyễn Tuấn Kiệt cần bổ sung bản cứng.',
    time: 'Hôm qua',
    priority: 'normal',
    status: 'read',
    actionLabel: 'Xem hợp đồng',
    tone: 'violet',
    icon: FileText,
    detail: {
      code: 'CONTRACT-007',
      createdAt: '14/08/2026 16:20',
      source: 'Hợp đồng',
      owner: 'CSKH',
      priorityLabel: 'Chờ bổ sung',
      content: 'Hợp đồng đã tạo trên hệ thống nhưng thiếu bản cứng có chữ ký. Cần nhắc phụ huynh bổ sung trong buổi học tiếp theo.',
      fields: [
        { label: 'Mã hợp đồng', value: 'HD-2026-0811-01' },
        { label: 'Học viên', value: 'Nguyễn Tuấn Kiệt' },
        { label: 'Tình trạng', value: 'Chờ bổ sung chữ ký' },
        { label: 'Người phụ trách', value: 'Quốc Việt' },
      ],
    },
  },
  {
    id: 'noti-teacher-leave-008',
    type: 'staff',
    title: 'Giáo viên xin nghỉ',
    message: 'Trần Thị B gửi yêu cầu nghỉ phép ngày 17/08/2026, cần sắp giáo viên thay thế.',
    time: 'Hôm qua',
    priority: 'urgent',
    status: 'read',
    actionLabel: 'Xử lý lịch',
    tone: 'amber',
    icon: Users,
    detail: {
      code: 'STAFF-LEAVE-008',
      createdAt: '14/08/2026 09:15',
      source: 'Nhân sự',
      owner: 'Điều phối đào tạo',
      priorityLabel: 'Cần xếp thay thế',
      content: 'Giáo viên có lịch dạy trong ngày nghỉ phép. Cần kiểm tra lớp bị ảnh hưởng và gửi thông báo đổi giáo viên nếu cần.',
      fields: [
        { label: 'Giáo viên', value: 'Trần Thị B' },
        { label: 'Ngày nghỉ', value: '17/08/2026' },
        { label: 'Lý do', value: 'Nghỉ phép cá nhân' },
        { label: 'Lớp ảnh hưởng', value: '2 lớp' },
      ],
    },
  },
  {
    id: 'noti-campaign-009',
    type: 'marketing',
    title: 'Chiến dịch vượt ngân sách',
    message: 'Facebook Lead Ads tháng 8 đã dùng 92% ngân sách nhưng mới đạt 76% mục tiêu lead.',
    time: '12/08/2026',
    priority: 'normal',
    status: 'read',
    actionLabel: 'Xem chiến dịch',
    tone: 'fuchsia',
    icon: Megaphone,
    detail: {
      code: 'MKT-BUDGET-009',
      createdAt: '12/08/2026 18:00',
      source: 'Marketing',
      owner: 'Marketing & Sale',
      priorityLabel: 'Theo dõi hiệu quả',
      content: 'Chiến dịch đang tiêu ngân sách nhanh hơn tiến độ lead. Cần xem lại target, nội dung quảng cáo và chi phí mỗi lead.',
      fields: [
        { label: 'Chiến dịch', value: 'Facebook Lead Ads tháng 8' },
        { label: 'Ngân sách đã dùng', value: '92%' },
        { label: 'Mục tiêu đạt được', value: '76%' },
        { label: 'Đề xuất', value: 'Tối ưu nhóm quảng cáo chi phí cao' },
      ],
    },
  },
  {
    id: 'noti-system-010',
    type: 'system',
    title: 'Phân quyền vừa được cập nhật',
    message: 'Nhóm Tài chính được thêm quyền xuất báo cáo doanh thu.',
    time: '11/08/2026',
    priority: 'normal',
    status: 'read',
    actionLabel: 'Xem cài đặt',
    tone: 'slate',
    icon: ShieldCheck,
    detail: {
      code: 'SYS-PERM-010',
      createdAt: '11/08/2026 10:25',
      source: 'Hệ thống',
      owner: 'Quản trị viên',
      priorityLabel: 'Đã cập nhật',
      content: 'Quyền xuất báo cáo doanh thu đã được mở cho nhóm Tài chính. Nên rà soát lại danh sách nhân sự thuộc nhóm quyền này.',
      fields: [
        { label: 'Nhóm quyền', value: 'Tài chính' },
        { label: 'Quyền mới', value: 'Xuất báo cáo doanh thu' },
        { label: 'Người cập nhật', value: 'Quản trị viên' },
        { label: 'Thời gian', value: '11/08/2026 10:25' },
      ],
    },
  },
]
