import { AlertCircle, BellRing, CheckCircle2, CreditCard, MessageCircle, UsersRound } from 'lucide-react'

export const parentStatus = [
  { label: 'Đang đồng hành', value: 'active', badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { label: 'Cần chăm sóc', value: 'care', badgeClass: 'bg-amber-50 text-amber-700 border-amber-200' },
  { label: 'Công nợ', value: 'debt', badgeClass: 'bg-rose-50 text-rose-700 border-rose-200' },
  { label: 'Tạm ngưng', value: 'inactive', badgeClass: 'bg-slate-100 text-slate-700 border-slate-200' },
]

export const parentStatistics = [
  { label: 'Tổng phụ huynh', value: '1,086', description: 'Hồ sơ phụ huynh đang quản lý', icon: UsersRound, color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { label: 'Đang đồng hành', value: '912', description: 'Theo dõi học tập thường xuyên', icon: CheckCircle2, color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { label: 'Cần chăm sóc', value: '96', description: 'Cần tư vấn hoặc gọi lại', icon: AlertCircle, color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { label: 'Còn công nợ', value: '78', description: 'Có học phí/chứng từ cần xử lý', icon: CreditCard, color: 'bg-rose-50 text-rose-700 border-rose-200' },
]

export const parentCharts = {
  communication: [
    { month: 'T1', calls: 320, messages: 840, meetings: 52 },
    { month: 'T2', calls: 346, messages: 910, meetings: 61 },
    { month: 'T3', calls: 388, messages: 1024, meetings: 74 },
    { month: 'T4', calls: 412, messages: 1180, meetings: 82 },
    { month: 'T5', calls: 456, messages: 1268, meetings: 88 },
    { month: 'T6', calls: 498, messages: 1396, meetings: 94 },
    { month: 'T7', calls: 536, messages: 1484, meetings: 106 },
  ],
  status: [
    { name: 'Đồng hành tốt', value: 74, fill: '#10b981' },
    { name: 'Cần chăm sóc', value: 12, fill: '#f59e0b' },
    { name: 'Công nợ', value: 9, fill: '#ef4444' },
    { name: 'Tạm ngưng', value: 5, fill: '#64748b' },
  ],
  payment: [
    { branch: 'Cơ sở 1', paid: 218000000, debt: 28000000 },
    { branch: 'Cơ sở 2', paid: 174000000, debt: 21000000 },
    { branch: 'Cơ sở 3', paid: 136000000, debt: 18000000 },
  ],
}

export const parentFilters = {
  branches: ['Cơ sở 1', 'Cơ sở 2', 'Cơ sở 3'],
  classes: ['A12', 'K08', 'C05', 'I03', 'T11', 'K09', 'A13'],
  courses: ['IELTS Foundation', 'Kids Starter', 'Communication', 'Teen Grammar', 'IELTS Intensive'],
  careLevels: ['Ưu tiên cao', 'Theo dõi định kỳ', 'Ổn định'],
  statuses: parentStatus,
}

export const parents = [
  {
    id: 'PH001086',
    code: 'PH001086',
    name: 'Nguyễn Thị Lan',
    avatar: 'NL',
    phone: '0901 555 248',
    email: 'lan.nguyen@example.com',
    student: 'Nguyễn Minh Anh',
    studentCode: 'HV001248',
    relation: 'Mẹ',
    course: 'IELTS Foundation',
    className: 'A12',
    branch: 'Cơ sở 1',
    lastContact: '31/07/2026',
    careLevel: 'Ổn định',
    tuitionStatus: 'Đã thanh toán',
    debt: 0,
    attendanceAlert: 'Không',
    learningNote: 'Học viên tiến bộ tốt, phụ huynh phản hồi tích cực.',
    status: 'Đang đồng hành',
    statusValue: 'active',
    channels: ['Email', 'Zalo', 'SMS'],
  },
  {
    id: 'PH001085',
    code: 'PH001085',
    name: 'Trần Văn Đức',
    avatar: 'TD',
    phone: '0901 555 247',
    email: 'duc.tran@example.com',
    student: 'Trần Gia Bảo',
    studentCode: 'HV001247',
    relation: 'Ba',
    course: 'Kids Starter',
    className: 'K08',
    branch: 'Cơ sở 2',
    lastContact: '30/07/2026',
    careLevel: 'Theo dõi định kỳ',
    tuitionStatus: 'Chờ thu',
    debt: 6500000,
    attendanceAlert: 'Không',
    learningNote: 'Cần xác nhận lịch học thử và tư vấn lộ trình tiếp theo.',
    status: 'Cần chăm sóc',
    statusValue: 'care',
    channels: ['Zalo', 'SMS'],
  },
  {
    id: 'PH001084',
    code: 'PH001084',
    name: 'Lê Thị Hạnh',
    avatar: 'LH',
    phone: '0901 555 246',
    email: 'hanh.le@example.com',
    student: 'Lê Hoàng Nam',
    studentCode: 'HV001246',
    relation: 'Mẹ',
    course: 'Communication',
    className: 'C05',
    branch: 'Cơ sở 1',
    lastContact: '29/07/2026',
    careLevel: 'Ưu tiên cao',
    tuitionStatus: 'Còn 1 kỳ',
    debt: 4200000,
    attendanceAlert: 'Có',
    learningNote: 'Học viên bảo lưu, cần gọi phụ huynh xác nhận ngày quay lại.',
    status: 'Công nợ',
    statusValue: 'debt',
    channels: ['Điện thoại', 'Email'],
  },
  {
    id: 'PH001083',
    code: 'PH001083',
    name: 'Phạm Quốc Việt',
    avatar: 'PV',
    phone: '0901 555 245',
    email: 'viet.pham@example.com',
    student: 'Phạm Thảo Vy',
    studentCode: 'HV001245',
    relation: 'Ba',
    course: 'IELTS Intensive',
    className: 'I03',
    branch: 'Cơ sở 3',
    lastContact: '28/07/2026',
    careLevel: 'Ổn định',
    tuitionStatus: 'Đã thanh toán',
    debt: 0,
    attendanceAlert: 'Không',
    learningNote: 'Phụ huynh quan tâm mục tiêu IELTS 7.0, cần gửi báo cáo tháng.',
    status: 'Đang đồng hành',
    statusValue: 'active',
    channels: ['Email', 'Zalo'],
  },
  {
    id: 'PH001082',
    code: 'PH001082',
    name: 'Đỗ Minh Tâm',
    avatar: 'DT',
    phone: '0901 555 244',
    email: 'tam.do@example.com',
    student: 'Đỗ Khánh Linh',
    studentCode: 'HV001244',
    relation: 'Ba',
    course: 'Teen Grammar',
    className: 'T11',
    branch: 'Cơ sở 2',
    lastContact: '27/07/2026',
    careLevel: 'Theo dõi định kỳ',
    tuitionStatus: 'Đã thanh toán',
    debt: 0,
    attendanceAlert: 'Không',
    learningNote: 'Gửi nhắc lịch kiểm tra cuối tuần qua Zalo.',
    status: 'Đang đồng hành',
    statusValue: 'active',
    channels: ['Zalo'],
  },
  {
    id: 'PH001081',
    code: 'PH001081',
    name: 'Vũ Thị Ngọc',
    avatar: 'VN',
    phone: '0901 555 243',
    email: 'ngoc.vu@example.com',
    student: 'Vũ Anh Quân',
    studentCode: 'HV001243',
    relation: 'Mẹ',
    course: 'Kids Starter',
    className: 'K09',
    branch: 'Cơ sở 1',
    lastContact: '26/07/2026',
    careLevel: 'Ưu tiên cao',
    tuitionStatus: 'Còn nợ',
    debt: 7800000,
    attendanceAlert: 'Có',
    learningNote: 'Học viên nghỉ học nhiều, cần hẹn gặp phụ huynh trong tuần.',
    status: 'Tạm ngưng',
    statusValue: 'inactive',
    channels: ['Điện thoại', 'SMS'],
  },
  {
    id: 'PH001080',
    code: 'PH001080',
    name: 'Ngô Văn Bình',
    avatar: 'NB',
    phone: '0901 555 242',
    email: 'binh.ngo@example.com',
    student: 'Ngô Mai Chi',
    studentCode: 'HV001242',
    relation: 'Ba',
    course: 'IELTS Foundation',
    className: 'A13',
    branch: 'Cơ sở 3',
    lastContact: '25/07/2026',
    careLevel: 'Ổn định',
    tuitionStatus: 'Đã thanh toán',
    debt: 0,
    attendanceAlert: 'Không',
    learningNote: 'Đã gửi chứng nhận hoàn thành và phiếu đánh giá.',
    status: 'Đang đồng hành',
    statusValue: 'active',
    channels: ['Email', 'Zalo'],
  },
]

export const parentCareActivities = [
  { id: 'act-01', icon: MessageCircle, title: 'Gửi báo cáo học tập tháng 7', parent: 'Nguyễn Thị Lan', time: '31/07/2026 20:15', status: 'Đã gửi' },
  { id: 'act-02', icon: BellRing, title: 'Nhắc lịch thanh toán học thử', parent: 'Trần Văn Đức', time: '30/07/2026 09:10', status: 'Chờ phản hồi' },
  { id: 'act-03', icon: AlertCircle, title: 'Hẹn gặp xử lý nghỉ học nhiều', parent: 'Vũ Thị Ngọc', time: '29/07/2026 18:40', status: 'Ưu tiên cao' },
]
