import {
  GraduationCap,
  UserCheck,
  UserX,
} from 'lucide-react'

export const staffStatus = [
  { label: 'Đang làm việc', value: 'active', badgeClass: 'border-emerald-200 bg-emerald-50 text-emerald-700' },
  { label: 'Thử việc', value: 'probation', badgeClass: 'border-blue-200 bg-blue-50 text-blue-700' },
  { label: 'Tạm nghỉ', value: 'paused', badgeClass: 'border-amber-200 bg-amber-50 text-amber-700' },
  { label: 'Đã nghỉ việc', value: 'inactive', badgeClass: 'border-slate-200 bg-slate-100 text-slate-700' },
]

export const staffStatistics = [
  { label: 'Tổng giáo viên', value: 42, description: 'Giáo viên đang quản lý', icon: GraduationCap, color: 'border-blue-200 bg-blue-50 text-blue-700' },
  { label: 'Đang giảng dạy', value: 36, description: 'Giáo viên đang active', icon: UserCheck, color: 'border-emerald-200 bg-emerald-50 text-emerald-700' },
  { label: 'Tạm nghỉ', value: 4, description: 'Giáo viên cần theo dõi lịch', icon: UserX, color: 'border-amber-200 bg-amber-50 text-amber-700' },
  { label: 'Đã nghỉ việc', value: 2, description: 'Hồ sơ đã ngừng làm việc', icon: UserX, color: 'border-slate-200 bg-slate-100 text-slate-700' },
]

export const staffCharts = {
  departments: [
    { name: 'Đào tạo', value: 34 },
    { name: 'Học vụ', value: 16 },
    { name: 'Tư vấn', value: 18 },
    { name: 'Marketing', value: 8 },
    { name: 'Kế toán', value: 6 },
    { name: 'Vận hành', value: 4 },
  ],
  specialties: [
    { name: 'IELTS', value: 15, fill: '#2563eb' },
    { name: 'Kids', value: 10, fill: '#10b981' },
    { name: 'Communication', value: 8, fill: '#f59e0b' },
    { name: 'Grammar', value: 5, fill: '#8b5cf6' },
    { name: 'TOEIC', value: 4, fill: '#ef4444' },
  ],
  monthlyKpi: [
    { month: 'T1', score: 82 },
    { month: 'T2', score: 85 },
    { month: 'T3', score: 84 },
    { month: 'T4', score: 89 },
    { month: 'T5', score: 91 },
    { month: 'T6', score: 88 },
    { month: 'T7', score: 93 },
  ],
  kpiCompletion: [
    { name: 'Hoàn thành', value: 78, fill: '#10b981' },
    { name: 'Theo dõi', value: 16, fill: '#f59e0b' },
    { name: 'Chưa đạt', value: 6, fill: '#ef4444' },
  ],
}

export const staffs = [
  {
    id: 'STF001',
    code: 'NS001',
    avatar: 'NL',
    name: 'Nguyễn Hoàng Long',
    type: 'Giáo viên',
    typeValue: 'teacher',
    position: 'Giáo viên IELTS Senior',
    specialty: 'IELTS',
    department: 'Đào tạo',
    phone: '0901 222 334',
    email: 'long.nguyen@diichi.edu.vn',
    status: 'Đang làm việc',
    statusValue: 'active',
    startDate: '2024-03-12',
    birthDate: '1991-05-22',
    gender: 'Nam',
    citizenId: '079091000123',
    address: 'Quận 7, TP. Hồ Chí Minh',
    major: 'Ngôn ngữ Anh',
    degree: 'Thạc sĩ TESOL',
    experience: '9 năm',
    languages: 'Tiếng Anh C2, Tiếng Nhật N4',
    skills: ['IELTS Writing', 'Academic Coaching', 'Curriculum Design'],
  },
  {
    id: 'STF002',
    code: 'NS002',
    avatar: 'TM',
    name: 'Trần Thị Mai',
    type: 'Giáo viên',
    typeValue: 'teacher',
    position: 'Giáo viên Kids',
    specialty: 'Kids',
    department: 'Đào tạo',
    phone: '0908 555 112',
    email: 'mai.tran@diichi.edu.vn',
    status: 'Tạm nghỉ',
    statusValue: 'paused',
    startDate: '2023-08-01',
    birthDate: '1993-11-10',
    gender: 'Nữ',
    citizenId: '079193000456',
    address: 'Thủ Đức, TP. Hồ Chí Minh',
    major: 'Sư phạm Anh',
    degree: 'Cử nhân',
    experience: '6 năm',
    languages: 'Tiếng Anh C1',
    skills: ['Young Learners', 'Classroom Games', 'Phonics'],
  },
  {
    id: 'STF003',
    code: 'NS003',
    avatar: 'LH',
    name: 'Lê Quốc Huy',
    type: 'Giáo viên',
    typeValue: 'teacher',
    position: 'Giáo viên Communication',
    specialty: 'Communication',
    department: 'Đào tạo',
    phone: '0912 777 443',
    email: 'huy.le@diichi.edu.vn',
    status: 'Đang làm việc',
    statusValue: 'active',
    startDate: '2022-06-18',
    birthDate: '1989-09-04',
    gender: 'Nam',
    citizenId: '079089000789',
    address: 'Bình Thạnh, TP. Hồ Chí Minh',
    major: 'Applied Linguistics',
    degree: 'Thạc sĩ',
    experience: '11 năm',
    languages: 'Tiếng Anh C2, Tiếng Hàn A2',
    skills: ['Speaking Coaching', 'Pronunciation', 'Corporate Training'],
  },
  {
    id: 'STF004',
    code: 'NS004',
    avatar: 'PC',
    name: 'Phạm Minh Châu',
    type: 'Giáo viên',
    typeValue: 'teacher',
    position: 'Giáo viên IELTS Intensive',
    specialty: 'IELTS',
    department: 'Đào tạo',
    phone: '0933 101 606',
    email: 'chau.pham@diichi.edu.vn',
    status: 'Đang làm việc',
    statusValue: 'active',
    startDate: '2021-02-20',
    birthDate: '1988-12-16',
    gender: 'Nữ',
    citizenId: '079188000222',
    address: 'Quận 3, TP. Hồ Chí Minh',
    major: 'TESOL',
    degree: 'CELTA',
    experience: '12 năm',
    languages: 'Tiếng Anh C2',
    skills: ['IELTS Speaking', 'Mock Test', 'Teacher Training'],
  },
  {
    id: 'STF005',
    code: 'NS005',
    avatar: 'AK',
    name: 'Đỗ Anh Khoa',
    type: 'Nhân viên',
    typeValue: 'staff',
    position: 'Cố vấn học tập',
    specialty: 'Academic Care',
    department: 'Học vụ',
    phone: '0977 661 200',
    email: 'khoa.do@diichi.edu.vn',
    status: 'Đang làm việc',
    statusValue: 'active',
    startDate: '2023-01-09',
    birthDate: '1995-01-25',
    gender: 'Nam',
    citizenId: '079095000444',
    address: 'Tân Bình, TP. Hồ Chí Minh',
    major: 'Quản trị giáo dục',
    degree: 'Cử nhân',
    experience: '5 năm',
    languages: 'Tiếng Anh B2',
    skills: ['Student Care', 'Parent Communication', 'Retention'],
  },
  {
    id: 'STF006',
    code: 'NS006',
    avatar: 'HN',
    name: 'Hoàng Bảo Ngọc',
    type: 'Nhân viên',
    typeValue: 'staff',
    position: 'Tư vấn tuyển sinh',
    specialty: 'Sales',
    department: 'Tư vấn',
    phone: '0966 804 115',
    email: 'ngoc.hoang@diichi.edu.vn',
    status: 'Thử việc',
    statusValue: 'probation',
    startDate: '2026-07-01',
    birthDate: '1998-04-03',
    gender: 'Nữ',
    citizenId: '079198000987',
    address: 'Gò Vấp, TP. Hồ Chí Minh',
    major: 'Marketing',
    degree: 'Cử nhân',
    experience: '2 năm',
    languages: 'Tiếng Anh B2',
    skills: ['CRM', 'Lead Nurturing', 'Consulting'],
  },
  {
    id: 'STF007',
    code: 'NS007',
    avatar: 'VT',
    name: 'Võ Thanh Tùng',
    type: 'Nhân viên',
    typeValue: 'staff',
    position: 'Kế toán',
    specialty: 'Finance',
    department: 'Kế toán',
    phone: '0988 401 778',
    email: 'tung.vo@diichi.edu.vn',
    status: 'Đang làm việc',
    statusValue: 'active',
    startDate: '2020-10-05',
    birthDate: '1987-07-30',
    gender: 'Nam',
    citizenId: '079087000321',
    address: 'Quận 10, TP. Hồ Chí Minh',
    major: 'Kế toán',
    degree: 'Cử nhân',
    experience: '13 năm',
    languages: 'Tiếng Anh B1',
    skills: ['Payroll', 'Tuition Reconciliation', 'Tax'],
  },
  {
    id: 'STF008',
    code: 'NS008',
    avatar: 'LL',
    name: 'Lâm Linh Lan',
    type: 'Nhân viên',
    typeValue: 'staff',
    position: 'Marketing Executive',
    specialty: 'Digital Marketing',
    department: 'Marketing',
    phone: '0919 002 778',
    email: 'lan.lam@diichi.edu.vn',
    status: 'Đã nghỉ việc',
    statusValue: 'inactive',
    startDate: '2022-11-15',
    birthDate: '1996-08-18',
    gender: 'Nữ',
    citizenId: '079196000654',
    address: 'Phú Nhuận, TP. Hồ Chí Minh',
    major: 'Truyền thông',
    degree: 'Cử nhân',
    experience: '4 năm',
    languages: 'Tiếng Anh B2',
    skills: ['Content', 'Ads', 'Event'],
  },
]

export const teacherKPIs = [
  { staffId: 'STF001', teachingHours: 86, classes: 5, students: 96, homeworkMarked: 184, testsMarked: 42, averageScore: 7.9, attendanceRate: '94%', studentRating: 4.8, managerRating: 4.7 },
  { staffId: 'STF002', teachingHours: 48, classes: 3, students: 52, homeworkMarked: 96, testsMarked: 18, averageScore: 8.1, attendanceRate: '92%', studentRating: 4.6, managerRating: 4.5 },
  { staffId: 'STF003', teachingHours: 72, classes: 4, students: 80, homeworkMarked: 130, testsMarked: 24, averageScore: 8.0, attendanceRate: '91%', studentRating: 4.7, managerRating: 4.6 },
  { staffId: 'STF004', teachingHours: 90, classes: 4, students: 64, homeworkMarked: 166, testsMarked: 38, averageScore: 8.3, attendanceRate: '96%', studentRating: 4.9, managerRating: 4.8 },
]

export const attendanceData = [
  { id: 'ATT001', staffId: 'STF001', title: '28/07/2026', date: '2026-07-28', checkIn: '08:10', checkOut: '17:40', totalHours: '8.5h', status: 'Đủ công' },
  { id: 'ATT002', staffId: 'STF001', title: '27/07/2026', date: '2026-07-27', checkIn: '08:20', checkOut: '17:30', totalHours: '8.1h', status: 'Đi muộn' },
  { id: 'ATT003', staffId: 'STF002', title: '28/07/2026', date: '2026-07-28', checkIn: '--', checkOut: '--', totalHours: '0h', status: 'Nghỉ phép' },
  { id: 'ATT004', staffId: 'STF005', title: '28/07/2026', date: '2026-07-28', checkIn: '08:00', checkOut: '17:10', totalHours: '8.2h', status: 'Đủ công' },
  { id: 'ATT005', staffId: 'STF006', title: '28/07/2026', date: '2026-07-28', checkIn: '08:05', checkOut: '17:05', totalHours: '8h', status: 'Đủ công' },
]

export const teachingSchedules = [
  { id: 'TS001', staffId: 'STF001', title: 'IELTS Foundation A12', date: '2026-07-28', view: 'Theo ngày', time: '18:00 - 20:00', room: 'P.201', course: 'IELTS Foundation' },
  { id: 'TS002', staffId: 'STF001', title: 'Kids Starter K09', date: '2026-07-29', view: 'Theo tuần', time: '17:30 - 19:00', room: 'P.201', course: 'Kids Starter' },
  { id: 'TS003', staffId: 'STF003', title: 'Communication C05', date: '2026-07-29', view: 'Theo tuần', time: '19:30 - 21:00', room: 'P.301', course: 'Communication' },
  { id: 'TS004', staffId: 'STF004', title: 'IELTS Intensive I03', date: '2026-07-30', view: 'Theo tháng', time: '08:00 - 11:00', room: 'Lab A', course: 'IELTS Intensive' },
]

export const managedClasses = [
  { id: 'MC001', staffId: 'STF001', className: 'IELTS Foundation A12', course: 'IELTS Foundation', students: 18, schedule: 'T2-T4 18:00' },
  { id: 'MC002', staffId: 'STF001', className: 'Kids Starter K09', course: 'Kids Starter', students: 12, schedule: 'T2-T4 17:30' },
  { id: 'MC003', staffId: 'STF002', className: 'Kids Starter K08', course: 'Kids Starter', students: 16, schedule: 'T3-T5 17:30' },
  { id: 'MC004', staffId: 'STF003', className: 'Communication C05', course: 'Communication', students: 20, schedule: 'T2-T6 19:30' },
  { id: 'MC005', staffId: 'STF004', className: 'IELTS Intensive I03', course: 'IELTS Intensive', students: 14, schedule: 'T7-CN 08:00' },
]

export const certificates = [
  { id: 'CER001', staffId: 'STF001', title: 'IELTS 8.5 Academic', issuer: 'British Council', issuedAt: '2024-01-20', expiresAt: '2026-01-20', status: 'Còn hiệu lực' },
  { id: 'CER002', staffId: 'STF001', title: 'TESOL Advanced', issuer: 'Arizona State University', issuedAt: '2023-08-10', expiresAt: 'Không thời hạn', status: 'Còn hiệu lực' },
  { id: 'CER003', staffId: 'STF004', title: 'CELTA', issuer: 'Cambridge', issuedAt: '2021-06-05', expiresAt: 'Không thời hạn', status: 'Còn hiệu lực' },
  { id: 'CER004', staffId: 'STF002', title: 'TKT Young Learners', issuer: 'Cambridge', issuedAt: '2022-03-18', expiresAt: 'Không thời hạn', status: 'Còn hiệu lực' },
]

export const accounts = [
  { staffId: 'STF001', username: 'long.nguyen', role: 'Teacher Lead', permissions: ['Lớp học', 'Điểm danh', 'Homework', 'Báo cáo'], status: 'Đang hoạt động', lastLogin: '2026-07-28 08:20' },
  { staffId: 'STF002', username: 'mai.tran', role: 'Teacher', permissions: ['Lớp học', 'Điểm danh'], status: 'Tạm khóa', lastLogin: '2026-07-27 15:45' },
  { staffId: 'STF005', username: 'khoa.do', role: 'Academic Staff', permissions: ['Học viên', 'Lớp học', 'Thông báo'], status: 'Đang hoạt động', lastLogin: '2026-07-28 09:05' },
  { staffId: 'STF006', username: 'ngoc.hoang', role: 'Consultant', permissions: ['CRM', 'Học viên', 'Báo cáo'], status: 'Đang hoạt động', lastLogin: '2026-07-28 10:12' },
]

export const staffFilters = {
  branches: ['Cơ sở 1', 'Cơ sở 2', 'Cơ sở 3'],
  positions: ['Giáo viên IELTS Senior', 'Giáo viên Kids', 'Giáo viên Communication', 'Giáo viên IELTS Intensive'],
  departments: ['Đào tạo'],
  specialties: ['IELTS', 'Kids', 'Communication', 'Grammar', 'TOEIC'],
  statuses: staffStatus,
  dateRanges: ['Hôm nay', '7 ngày tới', 'Tháng này', 'Tùy chỉnh'],
}

export const staffTabs = ['Dashboard', 'Danh sách giáo viên', 'Hồ sơ giáo viên']

export const staffDetailTabs = ['Thông tin', 'Chuyên môn', 'Lớp phụ trách', 'Lịch giảng dạy', 'Chấm công', 'KPI']

export const staffModalConfigs = {
  add: { title: 'Thêm giáo viên', submitText: 'Thêm giáo viên', intent: 'form' },
  edit: { title: 'Cập nhật giáo viên', submitText: 'Cập nhật', intent: 'form' },
  assignClass: { title: 'Phân công lớp', submitText: 'Phân công', intent: 'assign' },
  transferDepartment: { title: 'Chuyển bộ phận', submitText: 'Chuyển bộ phận', intent: 'department' },
  updateCertificate: { title: 'Cập nhật chứng chỉ', submitText: 'Cập nhật chứng chỉ', intent: 'certificate' },
  import: { title: 'Import Excel', submitText: 'Import dữ liệu', intent: 'import' },
  delete: { title: 'Xác nhận xóa', submitText: 'Xóa giáo viên', intent: 'danger' },
  updateSpecialty: { title: 'Cập nhật chuyên môn', submitText: 'Cập nhật', intent: 'specialty' },
  notify: { title: 'Gửi thông báo', submitText: 'Gửi thông báo', intent: 'message' },
  exportExcel: { title: 'Export Excel', submitText: 'Export Excel', intent: 'export' },
  exportPdf: { title: 'Export PDF', submitText: 'Export PDF', intent: 'export' },
  printProfile: { title: 'In hồ sơ giáo viên', submitText: 'In hồ sơ', intent: 'confirm' },
}
