import {
  ArchiveRestore,
  Ban,
  Bell,
  CalendarClock,
  CheckCircle2,
  Download,
  FileDown,
  FileSpreadsheet,
  GraduationCap,
  IdCard,
  Mail,
  MessageSquareText,
  MoveRight,
  PauseCircle,
  Printer,
  RefreshCcw,
  Trash2,
  Upload,
  UserCheck,
  UserPlus,
  UserRoundX,
  Users,
} from 'lucide-react'

export const studentStatus = [
  {
    label: 'Đang học',
    value: 'active',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  {
    label: 'Bảo lưu',
    value: 'reserved',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    label: 'Nghỉ học',
    value: 'stopped',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    label: 'Hoàn thành khóa',
    value: 'completed',
    badgeClass: 'bg-violet-50 text-violet-700 border-violet-200',
  },
  {
    label: 'Học thử',
    value: 'trial',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
  },
]

export const studentStatistics = [
  {
    label: 'Tổng học viên',
    value: '1,248',
    description: 'Toàn bộ hồ sơ học viên',
    icon: Users,
    color: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    label: 'Đang học',
    value: '986',
    description: 'Học viên đang theo lớp',
    icon: UserCheck,
    color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  {
    label: 'Bảo lưu',
    value: '84',
    description: 'Hồ sơ đang tạm dừng',
    icon: PauseCircle,
    color: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    label: 'Nghỉ học',
    value: '52',
    description: 'Học viên đã ngừng học',
    icon: UserRoundX,
    color: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    label: 'Hoàn thành khóa',
    value: '126',
    description: 'Đã hoàn tất chương trình',
    icon: GraduationCap,
    color: 'bg-violet-50 text-violet-700 border-violet-200',
  },
]

export const studentCharts = {
  monthly: [
    { month: 'T1', students: 92 },
    { month: 'T2', students: 116 },
    { month: 'T3', students: 128 },
    { month: 'T4', students: 154 },
    { month: 'T5', students: 172 },
    { month: 'T6', students: 186 },
    { month: 'T7', students: 164 },
    { month: 'T8', students: 198 },
  ],
  status: [
    { name: 'Đang học', value: 79, fill: '#10b981' },
    { name: 'Bảo lưu', value: 7, fill: '#f59e0b' },
    { name: 'Nghỉ học', value: 4, fill: '#ef4444' },
    { name: 'Hoàn thành khóa', value: 10, fill: '#8b5cf6' },
  ],
}

export const studentFilters = {
  courses: ['IELTS Foundation', 'Kids Starter', 'Communication', 'Teen Grammar', 'IELTS Intensive'],
  classes: ['A12', 'K08', 'C05', 'I03', 'T11', 'K09', 'A13'],
  teachers: ['Nguyễn Hoàng Long', 'Trần Thị Mai', 'Lê Quốc Huy', 'Phạm Minh Châu'],
  branches: ['Cơ sở 1', 'Cơ sở 2', 'Cơ sở 3'],
  statuses: studentStatus,
}

export const students = [
  {
    id: 'HV001248',
    code: 'HV001248',
    name: 'Nguyễn Minh Anh',
    avatar: 'MA',
    gender: 'Nữ',
    birthDate: '14/05/2012',
    phone: '0901 248 111',
    parent: 'Nguyễn Thị Lan',
    parentPhone: '0901 555 248',
    course: 'IELTS Foundation',
    className: 'A12',
    teacher: 'Nguyễn Hoàng Long',
    branch: 'Cơ sở 1',
    status: 'Đang học',
    statusValue: 'active',
    enrollmentDate: '27/07/2026',
    email: 'minhanh@example.com',
    attendance: '96%',
    score: '8.1',
    homework: '2 bài chưa chấm',
    tuition: 'Đã thanh toán',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001247',
    code: 'HV001247',
    name: 'Trần Gia Bảo',
    avatar: 'GB',
    gender: 'Nam',
    birthDate: '22/08/2015',
    phone: '0901 247 222',
    parent: 'Trần Văn Đức',
    parentPhone: '0901 555 247',
    course: 'Kids Starter',
    className: 'K08',
    teacher: 'Trần Thị Mai',
    branch: 'Cơ sở 2',
    status: 'Học thử',
    statusValue: 'trial',
    enrollmentDate: '26/07/2026',
    email: 'giabao@example.com',
    attendance: '100%',
    score: 'Khởi động',
    homework: '0 bài',
    tuition: 'Chờ thu',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001246',
    code: 'HV001246',
    name: 'Lê Hoàng Nam',
    avatar: 'HN',
    gender: 'Nam',
    birthDate: '03/11/2009',
    phone: '0901 246 333',
    parent: 'Lê Thị Hạnh',
    parentPhone: '0901 555 246',
    course: 'Communication',
    className: 'C05',
    teacher: 'Lê Quốc Huy',
    branch: 'Cơ sở 1',
    status: 'Bảo lưu',
    statusValue: 'reserved',
    enrollmentDate: '26/07/2026',
    email: 'hoangnam@example.com',
    attendance: '88%',
    score: '7.4',
    homework: '1 bài chưa nộp',
    tuition: 'Còn 1 kỳ',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001245',
    code: 'HV001245',
    name: 'Phạm Thảo Vy',
    avatar: 'TV',
    gender: 'Nữ',
    birthDate: '19/04/2007',
    phone: '0901 245 444',
    parent: 'Phạm Quốc Việt',
    parentPhone: '0901 555 245',
    course: 'IELTS Intensive',
    className: 'I03',
    teacher: 'Phạm Minh Châu',
    branch: 'Cơ sở 3',
    status: 'Đang học',
    statusValue: 'active',
    enrollmentDate: '25/07/2026',
    email: 'thaovy@example.com',
    attendance: '94%',
    score: '8.4',
    homework: '3 bài cần chấm',
    tuition: 'Đã thanh toán',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001244',
    code: 'HV001244',
    name: 'Đỗ Khánh Linh',
    avatar: 'KL',
    gender: 'Nữ',
    birthDate: '27/12/2010',
    phone: '0901 244 555',
    parent: 'Đỗ Minh Tâm',
    parentPhone: '0901 555 244',
    course: 'Teen Grammar',
    className: 'T11',
    teacher: 'Trần Thị Mai',
    branch: 'Cơ sở 2',
    status: 'Đang học',
    statusValue: 'active',
    enrollmentDate: '25/07/2026',
    email: 'khanhlinh@example.com',
    attendance: '91%',
    score: '7.8',
    homework: '0 bài',
    tuition: 'Đã thanh toán',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001243',
    code: 'HV001243',
    name: 'Vũ Anh Quân',
    avatar: 'AQ',
    gender: 'Nam',
    birthDate: '09/09/2016',
    phone: '0901 243 666',
    parent: 'Vũ Thị Ngọc',
    parentPhone: '0901 555 243',
    course: 'Kids Starter',
    className: 'K09',
    teacher: 'Nguyễn Hoàng Long',
    branch: 'Cơ sở 1',
    status: 'Nghỉ học',
    statusValue: 'stopped',
    enrollmentDate: '24/07/2026',
    email: 'anhquan@example.com',
    attendance: '62%',
    score: '6.2',
    homework: '5 bài chưa nộp',
    tuition: 'Còn nợ',
    certificate: 'Chưa cấp',
  },
  {
    id: 'HV001242',
    code: 'HV001242',
    name: 'Ngô Mai Chi',
    avatar: 'MC',
    gender: 'Nữ',
    birthDate: '01/02/2008',
    phone: '0901 242 777',
    parent: 'Ngô Văn Bình',
    parentPhone: '0901 555 242',
    course: 'IELTS Foundation',
    className: 'A13',
    teacher: 'Phạm Minh Châu',
    branch: 'Cơ sở 3',
    status: 'Hoàn thành khóa',
    statusValue: 'completed',
    enrollmentDate: '24/07/2026',
    email: 'maichi@example.com',
    attendance: '97%',
    score: '8.6',
    homework: 'Hoàn tất',
    tuition: 'Đã thanh toán',
    certificate: 'Đã cấp',
  },
]

export const studentActions = [
  { label: 'Thêm học viên', type: 'add', icon: UserPlus },
  { label: 'Cập nhật học viên', type: 'edit', icon: RefreshCcw },
  { label: 'Xóa học viên', type: 'delete', icon: Trash2 },
  { label: 'Import Excel', type: 'import', icon: Upload },
  { label: 'Export Excel', type: 'exportExcel', icon: FileSpreadsheet },
  { label: 'Export PDF', type: 'exportPdf', icon: FileDown },
  { label: 'In thẻ học viên', type: 'printCard', icon: IdCard },
  { label: 'In hồ sơ học viên', type: 'printProfile', icon: Printer },
  { label: 'Chuyển lớp', type: 'transfer', icon: MoveRight },
  { label: 'Bảo lưu', type: 'reserve', icon: PauseCircle },
  { label: 'Hủy bảo lưu', type: 'unreserve', icon: ArchiveRestore },
  { label: 'Nghỉ học', type: 'stop', icon: Ban },
  { label: 'Gia hạn khóa học', type: 'extend', icon: CalendarClock },
  { label: 'Cập nhật trạng thái', type: 'status', icon: CheckCircle2 },
  { label: 'Gửi thông báo', type: 'notify', icon: Bell },
  { label: 'Gửi Email', type: 'email', icon: Mail },
  { label: 'Gửi SMS', type: 'sms', icon: MessageSquareText },
  { label: 'Tải danh sách', type: 'download', icon: Download },
]

export const profileTabs = [
  'Thông tin',
  'Phụ huynh',
  'Khóa học',
  'Điểm danh',
  'Điểm số',
  'Homework',
  'Học phí',
  'Lịch sử',
  'Chứng chỉ',
]

export const studentAttendanceSessions = [
  {
    id: 'attendance-01',
    title: 'Buổi 1',
    date: '29/07/2026',
    lesson: 'Listening Practice - Unit 1',
    className: 'IELTS Foundation A12',
    teacher: 'Nguyễn Hoàng Long',
    status: 'Có mặt',
    checkIn: '18:02',
    note: 'Đi học đúng giờ, tham gia đầy đủ hoạt động nhóm.',
  },
  {
    id: 'attendance-02',
    title: 'Buổi 2',
    date: '31/07/2026',
    lesson: 'Speaking Workshop - Part 1',
    className: 'IELTS Foundation A12',
    teacher: 'Nguyễn Hoàng Long',
    status: 'Vắng',
    checkIn: '-',
    note: 'Phụ huynh báo nghỉ có phép trước giờ học.',
  },
  {
    id: 'attendance-03',
    title: 'Buổi 3',
    date: '03/08/2026',
    lesson: 'Grammar Review - Tenses',
    className: 'IELTS Foundation A12',
    teacher: 'Nguyễn Hoàng Long',
    status: 'Đi muộn',
    checkIn: '18:18',
    note: 'Đi muộn 15 phút, đã hoàn thành bài luyện tập cuối buổi.',
  },
]

export const studentScoreItems = [
  {
    id: 'score-01',
    title: 'Placement Test',
    date: '27/07/2026',
    subject: 'IELTS tổng quát',
    score: '8.1/9.0',
    rank: 'Tốt',
    teacher: 'Nguyễn Hoàng Long',
    note: 'Listening và Reading tốt, cần luyện thêm tốc độ phản xạ Speaking.',
  },
  {
    id: 'score-02',
    title: 'Mini Test Unit 1',
    date: '01/08/2026',
    subject: 'Grammar',
    score: '8.4/10',
    rank: 'Khá',
    teacher: 'Nguyễn Hoàng Long',
    note: 'Nắm chắc cấu trúc câu, còn nhầm một số dạng thì hoàn thành.',
  },
  {
    id: 'score-03',
    title: 'Speaking Checkpoint',
    date: '05/08/2026',
    subject: 'Speaking',
    score: '7.5/9.0',
    rank: 'Khá',
    teacher: 'Nguyễn Hoàng Long',
    note: 'Phát âm rõ hơn, nên bổ sung từ vựng theo chủ đề gia đình.',
  },
]

export const studentHomeworkItems = [
  {
    id: 'homework-01',
    title: 'Listening Unit 1',
    deadline: '30/07/2026',
    status: 'Đã nộp',
    submittedAt: '30/07/2026 20:15',
    score: '9/10',
    note: 'Bài làm sạch, ghi chú từ mới đầy đủ.',
  },
  {
    id: 'homework-02',
    title: 'Speaking Recording Part 1',
    deadline: '02/08/2026',
    status: 'Chưa nộp',
    submittedAt: '-',
    score: 'Chưa chấm',
    note: 'Cần nhắc học viên nộp file ghi âm trước buổi tiếp theo.',
  },
  {
    id: 'homework-03',
    title: 'Vocabulary Topic School',
    deadline: '04/08/2026',
    status: 'Nộp muộn',
    submittedAt: '05/08/2026 09:30',
    score: '7/10',
    note: 'Nộp trễ 1 ngày, cần bổ sung ví dụ đặt câu.',
  },
]

export const studentTuitionItems = [
  {
    id: 'tuition-01',
    title: 'Học phí kỳ 1',
    dueDate: '30/07/2026',
    amount: '6.500.000đ',
    paidAmount: '6.500.000đ',
    status: 'Đã thanh toán',
    method: 'Chuyển khoản',
    note: 'Đã xuất biên nhận cho phụ huynh.',
  },
  {
    id: 'tuition-02',
    title: 'Phí giáo trình',
    dueDate: '05/08/2026',
    amount: '450.000đ',
    paidAmount: '0đ',
    status: 'Đến hạn',
    method: 'Chưa thanh toán',
    note: 'Nhắc phụ huynh thanh toán khi nhận giáo trình.',
  },
  {
    id: 'tuition-03',
    title: 'Học phí kỳ 2',
    dueDate: '25/08/2026',
    amount: '6.500.000đ',
    paidAmount: '0đ',
    status: 'Chưa đến hạn',
    method: 'Chưa thanh toán',
    note: 'Tự động gửi thông báo trước hạn 5 ngày.',
  },
]

export const studentHistoryItems = [
  {
    id: 'history-01',
    title: 'Tạo hồ sơ học viên',
    date: '27/07/2026',
    actor: 'Tư vấn viên Mai Anh',
    type: 'Hồ sơ',
    note: 'Tạo hồ sơ từ lead đăng ký học thử.',
  },
  {
    id: 'history-02',
    title: 'Xếp lớp A12',
    date: '28/07/2026',
    actor: 'Quản trị viên',
    type: 'Lớp học',
    note: 'Xếp vào lớp IELTS Foundation A12 sau bài kiểm tra đầu vào.',
  },
  {
    id: 'history-03',
    title: 'Gửi thông báo học phí',
    date: '29/07/2026',
    actor: 'Hệ thống',
    type: 'Thông báo',
    note: 'Đã gửi email và SMS nhắc lịch thanh toán kỳ 1.',
  },
]

export const studentCertificateItems = [
  {
    id: 'certificate-01',
    title: 'Chứng nhận hoàn thành Foundation',
    date: 'Dự kiến 30/10/2026',
    status: 'Chưa cấp',
    issuer: 'Di-Ichi English Center',
    score: 'Chờ tổng kết',
    note: 'Cấp sau khi hoàn thành tối thiểu 80% số buổi và đủ điểm cuối khóa.',
  },
  {
    id: 'certificate-02',
    title: 'Phiếu đánh giá đầu vào',
    date: '27/07/2026',
    status: 'Đã cấp',
    issuer: 'Phòng đào tạo',
    score: '8.1/9.0',
    note: 'Dùng làm căn cứ xếp lớp IELTS Foundation.',
  },
]

export const modalConfigs = {
  add: { title: 'Thêm học viên', submitText: 'Lưu học viên' },
  edit: { title: 'Cập nhật học viên', submitText: 'Cập nhật' },
  transfer: { title: 'Chuyển lớp', submitText: 'Xác nhận chuyển lớp' },
  reserve: { title: 'Bảo lưu', submitText: 'Xác nhận bảo lưu' },
  stop: { title: 'Nghỉ học', submitText: 'Xác nhận nghỉ học' },
  extend: { title: 'Gia hạn khóa học', submitText: 'Gia hạn' },
  import: { title: 'Import Excel', submitText: 'Tải lên' },
  delete: { title: 'Xác nhận xóa', submitText: 'Xóa học viên' },
}
